[window]
opacity = 0.7
startup_mode = "Maximized"
decorations = "None"
padding = { x=10, y=10}
blur = true
decorations_theme_variant = "Dark"

[colors]
[colors.primary]
background="#000000"

[colors.normal]
black  = "#000000"
white  = "#ffffff"
red    = "#ff0000"
green  = "#00ff00"
blue   = "#0000ff"
yellow = "#ffff00"
cyan   = "#00ffff"
magenta= "#ff00ff"

[font]
normal = { family = "sono", style="semibold"}
bold   = { family = "sono", style="extrabold"}

size =12
glyph_offset={x=0,y=0}
builtin_box_drawing=false
offset={x=-1,y=0}

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
